let products=JSON.parse(localStorage.getItem("products")||"[]"),currentProductId=null,activeTabSelected=!0;function save(){localStorage.setItem("products",JSON.stringify(products))}function calcStats(t){let e=t.transactions.reduce((t,e)=>t+e.amount,0),a=t.initial;return{invested:a,withdrawn:e,profit:e-a}}function formatCurrency(t){let e=t.toLocaleString("en-IN",{minimumFractionDigits:t%1!=0?2:0,maximumFractionDigits:2});return"₹"+e}function getLastTransactionDate(t){return 0===t.transactions.length?null:Math.max(...t.transactions.map(t=>t.date))}function formatTransactionDate(t){if(!t)return"No transactions";let e=new Date(t);return e.toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric"})}function updateOverall(){let t=products.filter(t=>activeTabSelected?!t.disabled:t.disabled),e=0,a=0;t.forEach(t=>{e+=t.initial,a+=t.transactions.reduce((t,e)=>t+e.amount,0)});let n=a-e;document.getElementById("totalInvested").textContent=formatCurrency(e),document.getElementById("totalWithdrawn").textContent=formatCurrency(a);let s=document.getElementById("totalPL");s.textContent=formatCurrency(n),s.className=n>=0?"overall-stats-value profit-positive":"overall-stats-value profit-negative"}function updateTabCounts(){document.getElementById("activeCount").textContent=products.filter(t=>!t.disabled).length,document.getElementById("inactiveCount").textContent=products.filter(t=>t.disabled).length}function updateTabUI(){document.getElementById("activeTab").classList.toggle("active",activeTabSelected),document.getElementById("inactiveTab").classList.toggle("active",!activeTabSelected)}function renderDashboard(){let t=document.getElementById("productList");t.innerHTML="";let e=products.filter(t=>activeTabSelected?!t.disabled:t.disabled).sort((t,e)=>(getLastTransactionDate(e)||0)-(getLastTransactionDate(t)||0));if(0===e.length){let a=document.createElement("div");a.className="empty-state",a.innerHTML=`
      <i class="fas fa-${activeTabSelected?"chart-line":"archive"}"></i>
      <p>No ${activeTabSelected?"active":"inactive"} investments found.</p>
    `,t.appendChild(a)}else e.forEach(e=>{let{invested:a,withdrawn:n,profit:s}=calcStats(e),i=getLastTransactionDate(e),l=document.createElement("li");l.className=`product-item ${e.disabled?"disabled":""}`,l.dataset.id=e.id,l.innerHTML=`
        <div class="product-header">
          <h3 class="product-name">${e.name}
            <span class="status-indicator ${e.disabled?"status-inactive":"status-active"}">
              ${e.disabled?"Inactive":"Active"}
            </span>
          </h3>
          <div class="last-transaction">
            <i class="fas fa-calendar-alt"></i> ${formatTransactionDate(i)}
          </div>
        </div>
        <div class="stats">
          <span class="stats-item"><i class="fas fa-arrow-circle-down"></i> INV: <span class="stats-value">${formatCurrency(a)}</span></span>
          <span class="stats-item"><i class="fas fa-arrow-circle-up"></i> WTD: <span class="stats-value">${formatCurrency(n)}</span></span>
          <span class="stats-item"><i class="fas fa-exchange-alt"></i> P/L: <span class="stats-value ${s>=0?"profit-positive":"profit-negative"}">${formatCurrency(s)}</span></span>
        </div>
      `,l.onclick=()=>openDetail(e.id),t.appendChild(l)});updateOverall(),updateTabCounts(),updateTabUI()}function renderDetail(t){document.getElementById("productTitle").textContent=t.name;let e=document.getElementById("toggleStatusBtn");e.innerHTML=t.disabled?'<i class="fas fa-check-circle"></i> Enable':'<i class="fas fa-ban"></i> Disable',e.className=t.disabled?"btn-outline btn-enable":"btn-outline btn-disable";let{invested:a,withdrawn:n,profit:s}=calcStats(t);document.getElementById("investedAmount").textContent=formatCurrency(a),document.getElementById("withdrawnAmount").textContent=formatCurrency(n);let i=document.getElementById("profitAmount");i.textContent=formatCurrency(s),i.className=s>=0?"detail-stats-value profit-positive":"detail-stats-value profit-negative",document.getElementById("withdrawalForm").classList.toggle("hidden",t.disabled);let l=document.getElementById("transactionList");l.innerHTML="";let d=t.createdDate?t.createdDate:parseInt(t.id,10),r=[{date:d,amount:-t.initial,isInitial:!0},...t.transactions.map(t=>({date:t.date,amount:t.amount,isInitial:!1}))];r.sort((t,e)=>e.date-t.date),r.forEach(t=>{let e=document.createElement("li");e.className="transaction-item";let a=t.isInitial?"-":"+",n=Math.abs(t.amount),s=t.isInitial?"transaction-inv-amount":"transaction-amount";e.innerHTML=`
      <span class="transaction-date">
        <i class="fas fa-calendar-alt"></i>
        ${formatTransactionDate(t.date)}
      </span>
      <span class="${s}">
        ${a} ${formatCurrency(n)}
      </span>
    `,l.appendChild(e)})}const dashboardEl=document.querySelector(".dashboard"),detailEl=document.querySelector(".detail-view"),openBtn=document.getElementById("openModal"),backBtn=document.getElementById("backBtn");function openDetail(t){currentProductId=t;let e=products.find(e=>e.id===t);dashboardEl.classList.add("exit-left"),detailEl.classList.remove("exit-right","hidden"),detailEl.classList.add("active"),openBtn.classList.add("hidden"),setTimeout(()=>{dashboardEl.classList.remove("active","exit-left"),dashboardEl.classList.add("hidden")},300),renderDetail(e)}backBtn.onclick=()=>{detailEl.classList.add("exit-right"),dashboardEl.classList.remove("hidden"),dashboardEl.classList.add("active"),setTimeout(()=>{detailEl.classList.remove("active","exit-right"),detailEl.classList.add("hidden"),openBtn.classList.remove("hidden")},300),window.scrollTo(0,0),renderDashboard()};let touchStartX=0;detailEl.addEventListener("touchstart",t=>{touchStartX=t.changedTouches[0].screenX}),detailEl.addEventListener("touchend",t=>{let e=t.changedTouches[0].screenX;e-touchStartX>50&&backBtn.click()}),document.getElementById("withdrawBtn").onclick=()=>{let t=parseFloat(document.getElementById("withdrawInput").value);if(!isNaN(t)&&t>0&&currentProductId){let e=products.find(t=>t.id===currentProductId);e.transactions.push({amount:t,date:Date.now()}),save(),renderDetail(e),document.getElementById("withdrawInput").value=""}},document.getElementById("toggleStatusBtn").onclick=()=>{let t=products.find(t=>t.id===currentProductId);t.disabled=!t.disabled,save(),renderDetail(t)},document.getElementById("activeTab").onclick=()=>{activeTabSelected=!0,renderDashboard()},document.getElementById("inactiveTab").onclick=()=>{activeTabSelected=!1,renderDashboard()};const modal=document.getElementById("modalBackdrop");openBtn.onclick=()=>{modal.style.display="flex",document.getElementById("productName").focus()},document.getElementById("cancelModal").onclick=()=>{modal.style.display="none"},document.getElementById("saveProduct").onclick=()=>{let t=document.getElementById("productName"),e=document.getElementById("initialInvestment"),a=t.value.trim(),n=parseFloat(e.value);a&&!isNaN(n)&&n>=0?(products.push({id:Date.now().toString(),name:a,initial:n,transactions:[],disabled:!1,createdDate:Date.now()}),save(),t.value="",e.value="",modal.style.display="none",activeTabSelected=!0,renderDashboard()):(a||(t.style.borderColor="var(--danger)"),(isNaN(n)||n<0)&&(e.style.borderColor="var(--danger)"))},document.getElementById("productName").addEventListener("input",t=>{t.target.style.borderColor="var(--border-color)"}),document.getElementById("initialInvestment").addEventListener("input",t=>{t.target.style.borderColor="var(--border-color)"}),renderDashboard(),updateTabUI();
